name: 'dbtrepo'
version: '1.0.0'
config-version: 2

profile: 'dalgo_dsf'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbtrepo:
    +materialized: view

    staging:
      +schema: staging

    prod:
      +schema: prod
      +materialized: table
