name: 'dalgo_dsf'
version: '1.0.0'
config-version: 2

profile: 'dalgo_dsf'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  dalgo_dsf:
    staging:
      +materialized: table
      pup01:
        +schema: staging
      hpn02:
        +schema: staging
      sft03:
        +schema: staging
      hpa04:
        +schema: staging
    marts:
      +materialized: table
      pup01:
        +schema: prod
      hpn02:
        +schema: prod
      sft03:
        +schema: prod
      hpa04:
        +schema: prod
    prod:
      +materialized: table

  elementary:
    +schema: "elementary"