version: 2

sources:
  - name: staging
    database: postgres
    schema: staging
    tables:
      - name: pp_raw_data
        loaded_at_field: submission_date
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}

models:
  - name: stg_surveycto_visits
    columns:
      - name: submission_key
        tests:
          - not_null
          - unique

      - name: visit_date
        tests:
          - not_null