version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: merged_a_c
        identifier: Merged_A_C
        description: <table_description>

      - name: merged_a_s
        identifier: Merged_A_S
        description: <table_description>

      - name: merged_p_c
        identifier: Merged_P_C
        description: <table_description>

      - name: merged_p_s
        identifier: Merged_P_S
        description: <table_description>

      - name: pp_dsf_1_scto
        identifier: pp_dsf_1_scto
        description: <table_description>